name = "nautica"
main = "_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "PROXY_DB"
id = "b5b2d4e9ddf44d5382cba7fbac540536"
